### ISSUE TITLE
Installing Elastic Search

### ISSUE THREAD

**Issue by bhavikshah92** [ahmedkhan847/customcms#1]
Hello,

I'm also trying to implement Elastic Search on a PHP and MySQL Site but I'm unable to get start as I searched on it and found that we need to install composer first and then proceed further. Since my server is a shared hosting I'm unable to do the same. Can you help me out the other way to implement ES.

**Comment by ahmedkhan847** [comment]
install this project on your local machine then use composer to install required dependencies and then upload the vendor folder in your hosting

**Comment by bhavikshah92** [comment]
I have download composer and added vendor folder to the class folder of your code but when I'm searching anything it gives below error

Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\NoNodesAvailableException' with message 'No alive nodes found in your cluster' in C:\xampp\htdocs\customcms\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php:51 Stack trace: #0 C:\xampp\htdocs\customcms\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(71): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection() #1 C:\xampp\htdocs\customcms\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(89): Elasticsearch\Transport->getConnection() #2 C:\xampp\htdocs\customcms\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(188): Elasticsearch\Transport->performRequest('GET', '/blog/article/_...', Array, '{"query":{"matc...', Array) #3 C:\xampp\htdocs\customcms\class\vendor\react\promise\src\FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #4 C:\xampp\htdocs\cu in C:\xampp\htdocs\customcms\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php on line 51

**Comment by ahmedkhan847** [comment]
Have you installed elasticsearch on your local machine?

**Comment by bhavikshah92** [comment]
Thank you for the error.

Now when I'm updating the record I get below error

<b>Fatal error</b>:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {&quot;error&quot;:{&quot;root_cause&quot;:[{&quot;type&quot;:&quot;action_request_validation_exception&quot;,&quot;reason&quot;:&quot;Validation Failed: 1: script or doc is missing;&quot;}],&quot;type&quot;:&quot;action_request_validation_exception&quot;,&quot;reason&quot;:&quot;Validation Failed: 1: script or doc is missing;&quot;},&quot;status&quot;:400} in C:\xampp\htdocs\nnl\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:525
Stack trace:
#0 C:\xampp\htdocs\nnl\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(208): Elasticsearch\Connections\Connection-&gt;process4xxError(Array, Array, Array)
#1 C:\xampp\htdocs\nnl\vendor\react\promise\src\FulfilledPromise.php(25): Elasticsearch\Connections\Connection-&gt;Elasticsearch\Connections\{closure}(Array)
#2 C:\xampp\htdocs\nnl\vendor\guzzlehttp\ringphp\src\Future\CompletedFutureValue.php(55): React\Promise\FulfilledPromise-&gt;then(Object(Closure), NULL, NULL)
#3 C:\xampp\htdocs\nnl\vendor\guzzlehttp\ringphp\src\Core.php(341): GuzzleHttp\Ring\Future\Com in <b>C:\xampp\htdocs\nnl\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php</b> on line <b>525</b><br />

I have below data and type in my index

 $params = [
                    'index' => 'property',
                    'body' => [
                        'mappings' => [
                            'propertydetails' => [
                                'properties' => [
                                    'id' => [
                                        'type' => 'integer'
                                     
                                    ],
									'CAPRate' => [
                                        'type' => 'double'
                                     
                                    ],
                                    'ListingTitle' => [
                                        'type' => 'string'
                                     
                                    ],
									'ListPrice' => [
                                        'type' => 'double'
                                    ],
									'PropertyType' => [
                                        'type' => 'string'
                                     
                                    ],
									'State' => [
                                        'type' => 'string'
                                     
                                    ],
                                    'TenancySummary' => [
                                        'type' => 'string'
                                     
                                    ],
									'TermRemaining' => [
                                        'type' => 'integer'
                                    ],
                                    'PhotoName' => [
                                        'type' => 'string'
                                     
                                    ],
                                ]
                            ]
                        ]
                    ]
                ];
